
SELECT			ID AS [Görev Numarasý],
				SYSADM.BW_AUFTR_KOPF.STATUS AS [Durum Noktasý], 
                  SYSADM.BW_AUFTR_KOPF.DATUM_LIEFER_TAT AS [Teslim Tarihi], 
				  SYSADM.BW_AUFTR_KOPF.AH_NAME1 AS [Müþteri Adý], 
				  SYSADM.BW_AUFTR_KOPF.AL_NAME1 AS Sevkiyat, 
                  SYSADM.BW_AUFTR_KOPF.SU_QM_FAKT AS [Gorev Metrekaresi],
				  SYSADM.BW_AUFTR_KOPF.SU_GEWICHT AS [Görev Kg], 
				  CAST(SYSADM.BW_AUFTR_KOPF.SU_STUECK AS INT) AS [Görev Adeti], 
                 -- CASE WHEN (Teslim_Tarihi < DATUM_LIEFER_TAT) THEN 'Öteleme var.' WHEN (Teslim_Tarihi > DATUM_LIEFER_TAT) THEN 'Öne çekildi.' ELSE 'Deðiþiklik Yok.' END AS [Görev Deðiþikliði], 
                  SYSADM.BW_AUFTR_KOPF.DATUM_ERF AS [Kayýt Tarihi],
				  SYSADM.BW_AUFTR_KOPF.OR_FACHBERATER AS MT
FROM     [SYSADM].[BW_AUFTR_KOPF] 
WHERE  (SYSADM.BW_AUFTR_KOPF.STATUS > 1) AND (SYSADM.BW_AUFTR_KOPF.STATUS < 611) and DATEDIFF(MONTH,SYSADM.BW_AUFTR_KOPF.DATUM_LIEFER_TAT,GETDATE())<6
--AND DATEDIFF(MONTH,SYSADM.BW_AUFTR_KOPF.DATUM_ERF,GETDATE())>3






