SELECT	Q1.AUFNR AS GOREVNO,
		Q1.TOPLAM,
		Q1.BITEN,
		Q1.CAM,
		--Q1.TANIM,
		Q1.DATUM_PROD AS TARIH,
		Q1.AGG_BEZ AS HAT,
		Q1.POSNR AS POZ,
		CONVERT(INT,Q1.GENISLIK) AS GENISLIK,
		CONVERT(INT,Q1.YUKSEKLIK) AS YUKSEKLIK,
		Q1.POS_STATUS AS POZDURUMU,
		CONVERT(NVARCHAR,REPLACE(Q1.ROWID,'-','')) AS ROWID

		
				
FROM
(
	SELECT	
			AGG_BEZ,
			AZEIT.AUFNR,
			AGG_TYP,
			AGG_PRB,
			AGG_SERIENTAB,
			AZEIT.POSNR,
			AZEIT.STUECK AS TOPLAM,
			AZEIT.FERTIG AS BITEN,
			AZEIT.BOM_ID,
			ROW_NUMBER() OVER (PARTITION BY AUFNR,POSNR,AGG_BEZ,AGG_TYP/*,AZEIT.BOM_ID*/ ORDER BY AUFNR) AS RN,
			AZEIT.DATUM_PROD,
			--CASE WHEN STKL.STL_BEZ IS NULL THEN 'ISICAM' ELSE STKL.STL_BEZ END AS TANIM,
			POS.POS_STATUS,
			POS.PP_BREITE AS GENISLIK,
			POS.PP_HOEHE AS YUKSEKLIK,
			STKL.STL_BEZ AS CAM,
			AZEIT.ROWID 
		
	FROM SYSADM.ZW_AGGREGATE AS AGG
	INNER JOIN SYSADM.ZW_AUFTR_ZEIT AS AZEIT
	ON
	AGG.AGG_ID=AZEIT.AGG


	LEFT JOIN [ARDMAIN].[SYSADM].[BW_AUFTR_STKL] AS STKL
	ON 
	AZEIT.AUFNR=STKL.ID 
	AND 
	AZEIT.POSNR=STKL.POS_NR
	--AND AZEIT.BOM_ID=STKL.BOM_ID



	INNER JOIN [ARDMAIN].[SYSADM].[BW_AUFTR_POS] AS POS
	ON
	AZEIT.AUFNR=POS.ID
	AND
	AZEIT.POSNR=POS.POS_NR



	WHERE 
	AGG_TYP NOT IN (0,99)
	
	/*AND 
	AUFNR=212601
	*/
	AND 
	AZEIT.KZ_SELECTED=1
	AND
	STKL.STL_PRODART IN (1,2) 
	AND 
	STKL.STL_MOD=1 


	)Q1

WHERE 
q1.AUFNR=727760
and
--Q1.POSNR=1
--AND
Q1.RN IN(1,2)
/*
AND
Q1.POSNR= 4
*/
ORDER BY TARIH DESC,CAM,GOREVNO,AGG_PRB,POZ
--Q1.POSNR   ,AGG_PRB

/*
SELECT TOP 1000 * FROM SYSADM.ZW_AUFTR_ZEIT
ORDER BY PROD_ZEIT DESC
*/